import { Dimensions, StyleSheet } from 'react-native';
import { useAppTheme } from 'src/common/context/AppTheme';

const screenWidth = Dimensions.get('window').width;
const screenHeight = Dimensions.get('window').height;

export const useUserStyle = () => {
  const { theme } = useAppTheme();
  return StyleSheet.create({
    backgroundImg: {
      flex: 1,
      justifyContent: 'flex-start',
      alignItems: 'flex-start',
      width: '100%',
      height: '100%',
    },
    avatarBorder: {
      borderWidth: 2,
      borderColor: theme.colors.borderInverse,
      borderRadius: 55,
      width: 105,
      height: 105,
      marginBottom: theme.spacing.lg,
      marginHorizontal: 'auto',
    },
    closeButton: {
      marginRight: -6,
    },
    btnAddHeight: {
      height: screenHeight - 400,
    },
    loginMain: {
      alignSelf: 'center',
      maxWidth: 430,
      margin: 'auto',
      width: '100%',
      justifyContent: 'flex-end',
    },
    imageprofile: {
      borderWidth: theme.roundness.sm,
      borderColor: theme.colors.borderBase,
      borderRadius: 50,
      alignSelf: 'center',
      alignItems: 'center',
      padding: theme.spacing.sm,
      marginBottom: -30,
      top: -50,
      width: 100,
      height: 100,
    },
    profileicon: {
      position: 'absolute',
      bottom: 0,
      shadowColor: theme.colors.surfaceInverse,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.3,
      shadowRadius: theme.roundness.xs,
      right: 0,
      top: -35,
      left: 65,
      backgroundColor: theme.colors.surfaceBase,
      borderRadius: 50,
    },
    avatarImg: {
      backgroundColor: theme.colors.surfaceBase,
    },
    formLayout: {
      borderRadius: theme.roundness.lg,
      paddingHorizontal: theme.spacing.lg,
      paddingBottom: theme.spacing.xl * 2,
      borderWidth: 1,
      borderColor: theme.colors.borderDisabled,
      paddingTop: theme.spacing.lg,
      marginHorizontal: theme.spacing.sm,
      backgroundColor: theme.colors.surfaceBase,
      marginBottom: theme.spacing.xl,
      shadowColor: theme.colors.surfaceInverse,
      shadowOffset: {
        width: 0,
        height: 1,
      },
      shadowOpacity: 0.22,
      shadowRadius: 2.22,
      elevation: 3,
    },

    heading: {
      fontSize: theme.fontSize.textHeadingMedium,
      fontFamily: theme.fontFamily.semiBold,
      marginBottom: theme.spacing.xxl,
      color: theme.colors.textBody,
      textAlign: 'center',
    },
    headerHeading: {
      fontSize: theme.fontSize.textHeadingLarge,
      color: theme.colors.textDisabled,
      fontFamily: theme.fontFamily.bold,
      marginTop: theme.spacing.xl,
      marginBottom: theme.spacing.md,
    },
    headericon: {
      padding: 0,
      margin: 0,
      cursor: 'pointer',
      width: 35,
      height: 35,
    },
    ImageDimension: {
      width: 250,
      height: 100,
      margin: 'auto',
      paddingBottom: 12,
    },
    disabledcolor: {
      backgroundColor: theme.colors.surfaceSecondaryBase,
    },
    headingTxt: {
      color: theme.colors.textBody,
      fontFamily: theme.fontFamily.regular,
      fontSize: theme.fontSize.S2Subtitle,
      lineHeight: theme.fontSize.S2Subtitle * 1.4,
    },
    modalContainer: {
      backgroundColor: theme.colors.surfaceBase,
      borderRadius: theme.roundness.md,
      zIndex: 1000,
      paddingBottom: theme.spacing.lg,
      width: 567,
      maxWidth: '100%',
      margin: 'auto',
    },
    modalTitle: {
      fontSize: theme.fontSize.S1Subtitle,
      fontFamily: theme.fontFamily.semiBold,
      color: theme.colors.textBody,
    },
    menuItemBox: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      gap: theme.spacing.lg,
      paddingVertical: theme.spacing.md,
      borderBottomWidth: 1,
      borderStyle: 'solid',
      borderColor: theme.colors.borderDisabled,
    },
    modalHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      width: '100%',
      borderWidth: 1,
      borderBottomColor: theme.colors.borderLow,
      borderTopColor: 'transparent',
      borderStartColor: 'transparent',
      borderEndColor: 'transparent',
      paddingVertical: theme.spacing.sm,
      paddingHorizontal: theme.spacing.md,
    },
    logoHeader: {
      paddingHorizontal: theme.spacing.lg,
      paddingVertical: theme.spacing.lg * 2,
      width: '100%',
      alignItems: 'center',
    },
    formInput: {
      borderColor: theme.colors.borderMedium,
      backgroundColor: theme.colors.surfaceBase,
      borderRadius: theme.roundness.sm,
      padding: 0,
      height: 50,
      minWidth: 20,
      fontFamily: theme.fontFamily.medium,
      fontSize: theme.fontSize.textBodyMedium,
      color: theme.colors.textBody,
      borderWidth: 0,
    },
    loginInputRadius: {
      fontSize: theme.fontSize.textBodyMedium,
      height: 48,
      color: theme.colors.textBody,
      backgroundColor: theme.colors.surfaceBase,
      borderRadius: theme.roundness.xs,
    },
    txtWrap: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      marginTop: -theme.spacing.sm,
    },
    checkWrap: {
      flexDirection: 'row',
      alignItems: 'center',
    },
    checkTxt: {
      color: theme.colors.textBodyLight,
      fontFamily: theme.fontFamily.medium,
      fontSize: theme.fontSize.textBodyMedium,
    },
    forgotTxt: {
      fontSize: theme.fontSize.textBodyMedium,
      color: theme.colors.textSuccessDark,
      fontFamily: theme.fontFamily.semiBold,
    },

    loginBtn: {
      marginTop: '10%',
    },
    checkboxContainer: {
      flexDirection: 'row',
      alignItems: 'center',
      marginTop: theme.spacing.sm,
    },
    flatListRestro: {
      padding: theme.spacing.sm,
      alignItems: 'center',
    },
    imageDimension: {
      width: 250,
      height: 100,
      margin: 'auto',
      paddingBottom: theme.spacing.sm,
    },
    iconButton: {
      position: 'absolute',
      right: 5,
      top: 10,
      color: theme.colors.textBody,
    },
    flagPickerCustom: {
      flexDirection: 'row',
      alignItems: 'center',
      height: 51,
      justifyContent: 'center',
      borderWidth: 1,
      borderRadius: theme.roundness.sm,
      borderColor: theme.colors.borderMedium,
      backgroundColor: theme.colors.surfaceBase,
      columnGap: theme.spacing.xs,
    },
    languageSelector: {
      position: 'absolute',
      right: 20,
      top: 20,
    },
  });
};
