export enum AsyncStorageKey {
  LANGUAGE_KEY = 'USER_LANGUAGE',
  USER_ACCESS_TOKEN = 'USER_ACCESS_TOKEN',
  USER_REFRESH_TOKEN = 'USER_REFRESH_TOKEN',
  ADMIN_PROPERTIES = 'ADMIN_PROPERTIES',
  ROLE = 'ROLE',
  TENANT_ID = 'TENANT_ID',
}
