import { StyleSheet } from 'react-native';
import { useAppTheme } from 'src/common/context/AppTheme';

export const usePlansStyle = () => {
    const { theme } = useAppTheme();
    return StyleSheet.create({
        container: {
            // height: '100%',
            // width: '100%',
            // backgroundColor: '#F5F5F5',
        },
        headerContainer: {
            paddingHorizontal: theme.spacing.lg,
        },
        filterrow: {
            flexDirection:'row',
            marginBottom: theme.spacing.xs,
        },
        breadcrumbContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: theme.spacing.xs / 2,
        },
        breadcrumb: {
            fontSize: theme.fontSize.textBodyMedium,
            fontFamily: theme.fontFamily.regular,
            color: theme.colors.textBodyLight,
        },
        bredcrumActive: {
            color: theme.colors.textBody,
            fontFamily: theme.fontFamily.semiBold,
        },
        content: {
            paddingHorizontal: theme.spacing.lg,
            paddingVertical: theme.spacing.lg,
            backgroundColor: theme.colors.surfaceBase,
            margin: theme.spacing.md,
            borderRadius: theme.roundness.sm,
            borderWidth: 1,
            borderColor: theme.colors.borderLow,
        },
        pageTitle: {
            marginBottom: theme.spacing.md,
        },
        sectionCard: {
            position: 'relative',
            backgroundColor: theme.colors.surfaceBase,
            borderWidth: 1,
            borderColor: theme.colors.borderLow,
            borderRadius: theme.roundness.sm,
            padding: theme.spacing.lg,
            marginBottom: theme.spacing.md,
            shadowColor: theme.colors.surfaceInverse,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.06,
            shadowRadius: 8,
            elevation: 1,
            zIndex: 1,
        },
        sectionCardRaised: {
            zIndex: 20,
            elevation: 8,
        },
        sectionHeader: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'space-between',
            paddingBottom: theme.spacing.md,
            marginBottom: theme.spacing.md,
            borderBottomWidth: 1,
            borderBottomColor: theme.colors.borderLow,
        },
        sectionTitleWrap: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: theme.spacing.sm,
        },
        sectionIcon: {
            width: 34,
            height: 34,
            borderRadius: theme.roundness.xs,
            backgroundColor: theme.colors.surfaceLow,
            alignItems: 'center',
            justifyContent: 'center',
        },
        sectionTitle: {
            color: theme.colors.textHeading,
            fontFamily: theme.fontFamily.semiBold,
        },
        currencyPill: {
            minHeight: 34,
            paddingHorizontal: theme.spacing.md,
            borderRadius: theme.roundness.xs,
            backgroundColor: theme.colors.surfaceLow,
            alignItems: 'center',
            justifyContent: 'center',
        },
        currencyPillText: {
            color: theme.colors.textBody,
            fontFamily: theme.fontFamily.semiBold,
        },
        fieldLabel: {
            marginBottom: theme.spacing.xs,
        },
        dropdownInput: {
            borderColor: theme.colors.borderMedium,
            borderWidth: 1,
            borderRadius: theme.roundness.sm,
            paddingHorizontal: theme.spacing.md,
            backgroundColor: theme.colors.surfaceBase,
            height: 52,
        },
        dropdownInputActive: {
            borderColor: theme.colors.borderInverse,
            borderWidth: 1,
            shadowColor: theme.colors.surfaceInverse,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.08,
            shadowRadius: 8,
            elevation: 2,
        },
        dropdownContainer: {
            backgroundColor: theme.colors.surfaceBase,
            borderWidth: 1,
            borderColor: theme.colors.borderLow,
            borderRadius: theme.roundness.sm,
            overflow: 'hidden',
            shadowColor: theme.colors.surfaceInverse,
            shadowOffset: { width: 0, height: 8 },
            shadowOpacity: 0.12,
            shadowRadius: 16,
            elevation: 10,
            marginTop: theme.spacing.xs,
        },
        dropdownSearch: {
            height: 42,
            borderRadius: theme.roundness.xs,
            borderColor: theme.colors.borderMedium,
            color: theme.colors.textBody,
            fontSize: theme.fontSize.textBodyMedium,
            fontFamily: theme.fontFamily.regular,
            paddingHorizontal: theme.spacing.md,
            margin: theme.spacing.sm,
        },
        dropdownItem: {
            minHeight: 42,
            paddingHorizontal: theme.spacing.md,
            justifyContent: 'center',
            backgroundColor: theme.colors.surfaceBase,
        },
        dropdownItemSelected: {
            backgroundColor: theme.colors.surfaceLow,
        },
        dropdownItemText: {
            color: theme.colors.textBody,
        },
        dropdownItemTextSelected: {
            color: theme.colors.textHeading,
            fontFamily: theme.fontFamily.semiBold,
        },
        readonlyInput: {
            backgroundColor: theme.colors.surfaceLow,
        },
        title: {
            fontSize: 24,
            fontFamily: theme.fontFamily.bold,
            color: theme.colors.textHeading,
            marginBottom: theme.spacing.md,
        },
        toggleContainer: {
            flexDirection: 'row',
            alignItems: 'center',
            justifyContent: 'center',
            marginBottom: theme.spacing.xl,
            backgroundColor: theme.colors.borderLow,
            borderRadius: theme.roundness.sm,
            padding: theme.spacing.xs,
            alignSelf: 'center',
            minWidth: 400,
        },
        toggleButton: {
            flex: 1,
            paddingVertical: theme.spacing.sm,
            paddingHorizontal: theme.spacing.xxl,
            borderRadius: theme.roundness.sm,
            backgroundColor: 'transparent',
            alignItems: 'center',
            justifyContent: 'center',
        },
        toggleButtonActive: {
            backgroundColor: theme.colors.surfaceInverse,
            shadowColor: theme.colors.surfaceInverse,
            shadowOffset: { width: 0, height: 2 },
            shadowOpacity: 0.15,
            shadowRadius: 4,
            elevation: 2,
        },
        toggleText: {
            fontSize: theme.fontSize.textBodyLarge,
            fontFamily: theme.fontFamily.semiBold,
            color: theme.colors.textBody,
        },
        toggleTextActive: {
            color: theme.colors.textInverse,
        },
        plansContainer: {
            flexDirection: 'row',
            gap: theme.spacing.md,
            marginBottom: theme.spacing.lg,
            justifyContent: 'center',
        },
        planCard: {
            flex: 1,
            maxWidth: 280,
            backgroundColor: theme.colors.surfaceBase,
            borderRadius: theme.roundness.lg,
            borderWidth: 1,
            borderColor: theme.colors.borderMedium,
            padding: theme.spacing.md,
            position: 'relative',
        },
        planEditButton: {
            position: 'absolute',
            top: theme.spacing.sm,
            right: theme.spacing.sm,
            padding: theme.spacing.xs,
        },
        planCardSelected: {
            borderColor: '#000000',
            borderWidth: 2,
            backgroundColor: theme.colors.surfaceBase,
        },
        popularBadge: {
            position: 'absolute',
            top: -14,
            alignSelf: 'center',
            backgroundColor: theme.colors.surfaceInverse,
            paddingVertical: 6,
            paddingHorizontal: 20,
            borderRadius: theme.roundness.xl,
        },
        popularBadgeText: {
            fontSize: 11,
            fontFamily: theme.fontFamily.bold,
            color: theme.colors.textInverse,
            textTransform: 'uppercase',
            letterSpacing: 0.5,
        },
        planName: {
            fontSize: 20,
            fontFamily: theme.fontFamily.bold,
            color: theme.colors.textHeading,
            marginBottom: theme.spacing.xs,
            marginTop: theme.spacing.xs,
        },
        priceContainer: {
            flexDirection: 'row',
            alignItems: 'baseline',
            marginBottom: theme.spacing.md,
        },
        priceSymbol: {
            fontSize: 24,
            fontFamily: theme.fontFamily.bold,
            color: theme.colors.textHeading,
        },
        priceAmount: {
            fontSize: 36,
            fontFamily: theme.fontFamily.bold,
            color: theme.colors.textHeading,
        },
        pricePeriod: {
            fontSize: theme.fontSize.textBodyMedium,
            fontFamily: theme.fontFamily.regular,
            color: theme.colors.textBodyLight,
        },
        featuresList: {
            gap: theme.spacing.xs,
        },
        featureItem: {
            flexDirection: 'row',
            alignItems: 'flex-start',
            gap: theme.spacing.sm,
        },
        featureText: {
            fontSize: theme.fontSize.textBodyMedium,
            fontFamily: theme.fontFamily.regular,
            color: theme.colors.textBodyLight,
            flex: 1,
            lineHeight: theme.fontSize.textBodyMedium * 1.5,
        },
        comparisonSection: {
            backgroundColor: theme.colors.surfaceBase,
            borderRadius: theme.roundness.lg,
            padding: theme.spacing.md,
        },
        tableHeader: {
            flexDirection: 'row',
            paddingBottom: theme.spacing.sm,
            borderBottomWidth: 1,
            borderBottomColor: theme.colors.borderMedium,
            marginBottom: theme.spacing.sm,
        },
        tableHeaderCell: {
            flex: 1,
            fontSize: theme.fontSize.textBodyMedium,
            fontFamily: theme.fontFamily.bold,
            color: theme.colors.textHeading,
            textAlign: 'center',
        },
        tableHeaderCellFirst: {
            textAlign: 'left',
            flex: 2,
        },
        tableRow: {
            flexDirection: 'row',
            paddingVertical: theme.spacing.sm,
            borderBottomWidth: 1,
            borderBottomColor: theme.colors.borderLow,
            alignItems: 'center',
        },
        tableRowLast: {
            borderBottomWidth: 0,
        },
        tableCellText: {
            flex: 1,
            fontSize: theme.fontSize.textBodyMedium,
            fontFamily: theme.fontFamily.regular,
            color: theme.colors.textBodyLight,
            textAlign: 'center',
        },
        tableCellFirst: {
            flex: 2,
            fontSize: theme.fontSize.textBodyMedium,
            fontFamily: theme.fontFamily.regular,
            color: theme.colors.textBodyLight,
            textAlign: 'left',
        },
        tableCellIcon: {
            flex: 1,
            alignItems: 'center',
        },
        buttonContainer: {
            marginTop: theme.spacing.xl,
            alignItems: 'center',
            paddingBottom: theme.spacing.lg,
        },
        fullWidth: {
            width: '100%',
        },
        planShareWrapper: {
            width: '100%',
        },
        planShareLabel: {
            flexDirection: 'row',
            alignItems: 'center',
            gap: theme.spacing.sm,
            marginBottom: theme.spacing.sm,
        },
        planShareCard: {
            borderWidth: 1,
            borderColor: theme.colors.borderLow,
            borderRadius: theme.roundness.sm,
            padding: theme.spacing.md,
            width: '100%',
            backgroundColor: theme.colors.surfaceBase,
        },
        businessShareTabContainer: {
            flexDirection: 'row',
            alignSelf: 'center',
            backgroundColor: theme.colors.borderLow,
            borderRadius: theme.roundness.sm,
            gap: theme.spacing.xs,
            marginBottom: theme.spacing.md,
            padding: theme.spacing.xs,
        },
        businessShareTab: {
            minHeight: 42,
            alignItems: 'center',
            justifyContent: 'center',
            borderRadius: theme.roundness.xs,
            backgroundColor: 'transparent',
            paddingHorizontal: theme.spacing.xl,
        },
        businessShareTabActive: {
            backgroundColor: theme.colors.surfaceInverse,
        },
        businessShareTabText: {
            color: theme.colors.textBody,
            fontFamily: theme.fontFamily.semiBold,
        },
        businessShareTabTextActive: {
            color: theme.colors.textInverse,
        },
        rideAmountFields: {
            width: '100%',
        },
        rideAmountRow: {
            marginBottom: theme.spacing.lg,
        },
        rideAmountLastRow: {
            marginBottom: 0,
        },
        currencyInputAffix: {
            color: theme.colors.textBodyLight,
            fontFamily: theme.fontFamily.medium,
            fontSize: theme.fontSize.textBodyMedium,
            textAlign: 'center',
            width: '100%',
        },
        currencyInputIcon: {
            width: 52,
            height: 48,
            marginLeft: theme.spacing.xs,
            alignItems: 'center',
            justifyContent: 'center',
        },
        actionButtonContainer: {
            alignItems: 'flex-end',
            marginTop: theme.spacing.md,
        },
        editButtonContainer: {
            alignItems: 'flex-end',
        },
        actionButton: {
            minWidth: 130,
            height: 42,
            paddingVertical: theme.spacing.xs,
            paddingHorizontal: theme.spacing.lg,
        },
        continueButton: {
            backgroundColor: theme.colors.surfaceInverse,
            paddingVertical: theme.spacing.md,
            paddingHorizontal: theme.spacing.xl * 3,
            borderRadius: theme.roundness.md,
            elevation: 2,
            shadowColor: theme.colors.surfaceInverse,
            shadowOpacity: 0.2,
            shadowOffset: { width: 0, height: 2 },
            shadowRadius: theme.roundness.xs,
        },
        continueButtonText: {
            color: theme.colors.textInverse,
            fontSize: theme.fontSize.textButtonLarge,
            fontFamily: theme.fontFamily.semiBold,
            textAlign: 'center',
        },
    });
};
