export enum Routes {
  DEFAULT = '/home',
  LOGIN = '/login',
  REGISTRATION = '/registration',
  PROFILE = '/profile',
  UPLOAD = '/upload',
  Payment = '/payment',
  USER = '/users',
  REPORTS = '/reports',
  DASHBOARD = '/dashboard',
  NEWAPPLICATION = '/newApplication',
  MYAPPLICATION = '/myApplication',
  SCRUTINYREPORT = '/scrutinyReport',
  ARCHITECTDETAILS = '/architectDetail',
  


  CHANGE_PASSWORD = '/changePassword',
  RESTAURANTS = '/restaurants',
  PREVIEW = '/preview',
  NEW = '/new',
  SERVICE_AREAS = '/serviceAreas',
  MENU = '/menu',
  ADD = '/add',
  COUNTRIES = '/countries',
  STATES = '/states',
  CITIES = '/cities',

  RATE_TIERS = '/rateTiers',
  MENU_MANAGEMENT = '/management',
  REQUESTS = '/requestManagement',
  ONBOARDING = '/onboarding',
  DOCUMENTAPPROVAL = '/licenceinfo',
  SERVINGTIMING = '/timinginfo',
  CATEGORYINFO = '/categoryinfo',
  FEATURESIMAGES = '/imageinfo',
  DRIVER_ONBOARRDING = '/driverOnboarding',
  CUSTOMER = '/customer',
  WALLET = '/wallet',
  DRIVER = '/rider',
  CUSTOMERDETAILS = '/customerdetails',
  DRIVERDETAILS = '/driverdetails',
  DRIVER_LICENSE = '/driverLicense',
  DRIVER_BANK = '/driverBank',
  DRIVER_VEHICLE = '/driverVehicle',
  DRIVER_INSURANCE = '/driverInsurance',
  RESTAURANT = '/restaurant',
  ORDERDETAILS = '/orderDetails',
  ORDER = '/order',
  TAGS = '/tags',
  TICKET = '/ticket',
  COUPON = '/coupon',
  BANNER = '/banner',
  RESTAURANTWALLET = '/restaurantWallet',
  DRIVERWALLET = '/driverWallet',
  REPORT = '/report',
  BOOKINGHISTORY = '/bookingHistory',
  BOOKING = '/booking',
  BOOKINGDETAILS = '/bookingdetails',
  TRIPDETAILS = '/tripDetails',

  ROLES = '/roles',
  USERS = '/users',
  BUSINESS = '/business',
  PLANS = '/plans',
  INVOICING = '/invoicing',
  NEWBOOKING = '/newBooking',
  DRIVER_UPLOAD_PREVIEW = '/driverUploadPreview',
  TRIP_CHAT = '/tripChat',

  // Private architect
  DOCUMENT_VAULT = '/documentVault',

  // Super admin
  APPLICATIONS = '/applications',
  SCHEDULE_AWARDS = '/scheduleAwards',
  CERTIFICATES = '/certificates',
  DOCUMENT_STORE = '/documentStore',
  PERFORMANCE = '/performance',
  AUDIT_LOGS = '/auditLogs',
  SETTINGS = '/settings',
}
